# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [1]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [5]:
data_table = np.loadtxt('Desktop\ТОД\тема 1\data\minutes_n_ingredients.csv', dtype='int32', delimiter=',', skiprows=1)
print(data_table[0:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [7]:
print('среднее значение столбца №2: ', np.mean(data_table, axis=0)[1])
print('среднее значение столбца №3: ', np.mean(data_table, axis=0)[2])
print('минимум столбца №2: ', np.min(data_table, axis=0)[1])
print('минимум столбца №3: ', np.min(data_table, axis=0)[2])
print('максимум столбца №2: ', np.max(data_table, axis=0)[1])
print('максимум столбца №3: ', np.max(data_table, axis=0)[2])
print('медиана столбца №2: ', np.median(data_table, axis=0)[1])
print('медиана столбца №3: ', np.median(data_table, axis=0)[2])

среднее значение столбца №2:  21601.00169
среднее значение столбца №3:  9.05528
минимум столбца №2:  0
минимум столбца №3:  1
максимум столбца №2:  2147483647
максимум столбца №3:  39
медиана столбца №2:  40.0
медиана столбца №3:  9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [8]:
q = np.quantile(data_table[:, 1], q=0.75)
data_table[:, 1] = data_table[:, 1].clip(max=q)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [9]:
print(np.sum(data_table[:, 1]==0))
data_table[:, 1][data_table[:, 1]==0] = 1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [10]:
print(len(np.unique(data_table, axis=1)))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [13]:
print('количество различных значений числа ингредиентов: ', len(np.unique(data_table[:, 2])))
print('различные значения числа ингредиентов:')
print(np.unique(data_table[:, 2]))

количество различных значений числа ингредиентов:  37
различные значения числа ингредиентов:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [14]:
new_data = np.copy(data_table)
new_data[new_data[:, 2]<=5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [15]:
(data_table[:, 2] / data_table[:, 1]).max()

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [18]:
# отсортируем рецепты по убыванию продолжительности
sorted_data = data_table[data_table[:, 1].argsort()][::-1]
# первый вариант
print(np.average(sorted_data[:, 2][:100]))
# второй вариант
print(sorted_data[:, 2][:100].mean())

9.96
9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [22]:
print(data_table[np.random.randint(0, len(data_table), 10)])

[[149607     15      9]
 [ 61797     10      6]
 [115139     50     11]
 [458400     28      5]
 [160764     20      8]
 [247045     30     11]
 [137322     30      6]
 [431969     40     10]
 [456347     25     10]
 [479861     35      9]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [24]:
print(len(data_table[data_table[:, 2] < data_table[:, 2].mean()]) / len(data_table) * 100)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [26]:
simple = (data_table[:, 1] <= 20) & (data_table[:, 2] <= 5).astype('int32')
simple_recipe = np.insert(data_table, 3, simple, axis=1)
print(simple_recipe)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [27]:
print(len(simple_recipe[simple_recipe[:, 3] == 1]) / len(simple_recipe) * 100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [30]:
short = data_table[data_table[:, 1] < 10]
regular = data_table[(data_table[:, 1] >= 10) & (data_table[:, 1] < 20)]
long = data_table[data_table[:, 1] > 20]
max_count = min(map(len, [short, regular, long]))
a = np.vstack(([short[:max_count, :]], [regular[:max_count, :]], [long[:max_count, :]]))
print(a.shape)

(3, 7588, 3)
